### PR TITLE
Scrolling to note when highlighted

### PR DESCRIPTION
**Pull request by ivanacostarubio**
It helps when threads are enormous, 

> but it doesn't allow me to scroll afterward 😞  🤷🏼 ...

Maybe fix with https://github.com/v0l/snort/pull/160/commits/2edecfa3d2dba86304404bf19a4a69f99e85356e

Ex: 

- http://localhost:3000/e/note1uee992wd5gqqma86vhmzgxqsv7n0s9zxhrdu9lg6n62hjjeca7gqr4xqhr 
- http://localhost:3000/e/note17rrfw2eqdzg5t2zxa8sscp62fy4v94m9qjl55yaaj3e0u8r4qr9szwflrk

### CODE REVIEW

**Comment by verbiricha** [comment]
if we end up adding scroll I'd add this to CSS for smooth scrolling:

```css
html {
  scroll-behavior: smooth;
}
```

**Comment by ivanacostarubio** [comment]
Look how it renders

https://user-images.githubusercontent.com/16559/215274787-a5a81d27-d27a-44b0-9c4e-f4fc1499ffdc.mp4

**Comment by verbiricha** [comment]
I'm reworking threads atm and plan to implement this. I think we can close this one for the time being.

**Comment by ivanacostarubio** [comment]
:shipit:

**Pull request closed without merging**
