### PR TITLE
Skeleton component on timeline loading for better user experience

### PR DESCRIPTION
**Pull request by leotuna**
**Before 👇**
skeleton_before

**After 👇**
skeleton_after

### CODE REVIEW

**Comment by verbiricha** [comment]
Hey Leo, thanks for this. One problem I see though is that is only looking good in light mode, for dark mode looks too bright:

Screenshot 2023-02-02 at 08 15 04

I also think it'd be great to give the skeletons the same border radius as the notes instead of being square.

**Comment by leotuna** [comment]
What about now?
skeleton_2

**Review by Eiiki — COMMENTED** [review]
Great initiative 🙌  
I would suggest not passing the `Skeleton` as a child to the `LoadMore` component and just render it directly from it instead. I think it's safe as `LoadMore` is only rendered from the `Timeline` component so its only purpose should be to render the `Skeleton`.

**Comment by leotuna** [comment]
> Great initiative 🙌 I would suggest not passing the `Skeleton` as a child to the `LoadMore` component and just render it directly from it instead. I think it's safe as `LoadMore` is only rendered from the `Timeline` component so its only purpose should be to render the `Skeleton`.

Don't you think it should be reusable?

**Review by v0l — APPROVED** [review]
LGTM

**Pull request merged**
