### PR TITLE
Threads

### PR DESCRIPTION
**Pull request by verbiricha**

### CODE REVIEW

**Comment by verbiricha** [comment]
I'm going to tackle URL navigation separately, this can be reviewed already.

**Comment by v0l** [comment]
Soem threads are hidden, maybe if im clicking into a note which is on 3rd level or deeper then it only shows the root and the note i click on is hidden somewhere: 

https://threads.snort-social.pages.dev/e/note1ucc2nvd0ta9xqxjje6rmqkds745hyeglv4hv0c0xvfac2yzs656sjcn06r

**Comment by v0l** [comment]
Its still hiding this note, if i go to https://threads.snort-social.pages.dev/e/note1ucc2nvd0ta9xqxjje6rmqkds745hyeglv4hv0c0xvfac2yzs656sjcn06r it should show this note as focus? Right now i have to expand the Show more and there is no indication that its the selected note

**Comment by verbiricha** [comment]
@v0l my bad, accidentaly removed the highlight. Added it back, also expand subthreads when active is there.

**Comment by v0l** [comment]
Seems to not work still, when i navigate to post in a thread its highlighted at first but when the rest of the thread is loaded its buried

Instead of rendering the full thread we should skip to the level that the post is on and hide the upper levels?

**Comment by verbiricha** [comment]
@v0l can you take another 👀 ?

**Review by v0l — APPROVED** [review]
❤️

**Pull request merged**
