### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by petrikaj**

### CODE REVIEW

**Comment by h3y6e** [comment]
@petrikaj Hi, we handle translation tasks on Crowdin. We'd appreciate it if you could update here!
https://crowdin.com/project/snort

**Comment by petrikaj** [comment]
@h3y6e  Crowdin did not allow to import the file so it was agreed with Kieran to do this PR.

> @petrikaj Hi, we handle translation tasks on Crowdin. We'd appreciate it if you could update here! https://crowdin.com/project/snort

**Comment by h3y6e** [comment]
I see. In that case, since this is a mirror of https://git.v0l.io/Kieran/snort, it'd be best to send the PR there.

**Comment by h3y6e** [comment]
Oh, I haven't tried it myself, but it seems you can upload files from Crowdin.
https://support.crowdin.com/uploading-translations/#uploading-translations-via-language-page

**Comment by petrikaj** [comment]
@h3y6e Weblate accepts json. Crowdin takes XLIFF.

> Oh, I haven't tried it myself, but it seems you can upload files from Crowdin. https://support.crowdin.com/uploading-translations/#uploading-translations-via-language-page

**Comment by petrikaj** [comment]
@h3y6e 🤷‍♂️ I get only that error message now and when I tried that a few days ago.

snort_trans


> @petrikaj I tried uploading the json you created, and it worked. I apologize for doing this on my own... https://crowdin.com/project/snort/fi
> 
> > Crowdin takes XLIFF.

**Pull request closed without merging**
