### PR TITLE
Modified self-dm to be a "Note to Self"

### PR DESCRIPTION
**Pull request by LiranCohen**
Not sure if this is something you'd want but it's one of my favorite features of using Signal.

So I renamed the self DM to show as "Note to Self" with a book icon instead of your own, but still showing your nip5 underneath it (i thought it looked empty without it).

Also made it sticky to the top of the list so that it's easy to find.

I also added my nip-5 domain to have a nice gradient 😅

Please let me know if this is desirable and give any critique/review on how you'd want this better implemented.

Screenshots of how it looks:
Screenshot 2023-01-19 at 9 36 08 AM

Screenshot 2023-01-19 at 9 36 18 AM

### CODE REVIEW

**Review by verbiricha — APPROVED** [review]
This is a great improvement, thanks 🎉 

ACK to adding gradient to domains from people that have contributed to Snort, wdyt @v0l ?

**Comment by v0l** [comment]
Changes look good, Thanks!

I dont think it makes sense to give people colors for contributing because then people will just make PR's so they can get their own custom colors.

Alternatively we can give out free snort.social nip-05 to any contributors and they can use that if they want.

**Comment by LiranCohen** [comment]
I can remove my nip-05 gradient if you'd like. Will probably just have that patch for my own instance 😜

**Comment by v0l** [comment]
> I can remove my nip-05 gradient if you'd like. Will probably just have that patch for my own instance 😜

Yea please remove it, if you want a free snort.social nip5 just create an order and dont pay it, dm me and ill mark it as paid

**Pull request merged**
