### PR TITLE
German translations for snort

### PR DESCRIPTION
**Pull request by gandlafbtc**
Some translations, like `"{n,plural,=1{{n} new note} other{{n} new notes}}",` i didn't know to what extent they can be translated, so i left them unchanged

### CODE REVIEW

**Comment by v0l** [comment]
:O You did it manually? Why not with https://crowdin.com/project/snort

**Comment by gandlafbtc** [comment]
Oh! I didn't know about that! Should I do it again with the website?

**Comment by gandlafbtc** [comment]
I know someone who would do Korean. Is there an option for that?

**Comment by v0l** [comment]
> I know someone who would do Korean. Is there an option for that?

No its fine it should sync them again

> I know someone who would do Korean. Is there an option for that?

I will add Korean now! That would be awesome

**Review by v0l — APPROVED** [review]

**Pull request merged**
