### PR TITLE
Preferences & Profile changes

### PR DESCRIPTION
**Pull request by FlannelDipole**
Added: information on what the debug menu does, and added a helpful bit of text next to the private key to "not share it with anyone" to help new users out.

### CODE REVIEW

**Comment by verbiricha** [comment]
Thanks for these improvements @FlannelDipole ❤️ I've noticed that some files have been unintentionally, could you remove the files under `.idea` and the changes to `yarn.lock`? 🙏

**Comment by FlannelDipole** [comment]
Still new to working with .yarn, so I believe I made the proper changes as requested.

**Comment by verbiricha** [comment]
> Still new to working with .yarn, so I believe I made the proper changes as requested.

looks good, can you remove package-lock.json file as well?

**Comment by FlannelDipole** [comment]
> > Still new to working with .yarn, so I believe I made the proper changes as requested.
> 
> looks good, can you remove package-lock.json file as well?

Done and done.

**Review by verbiricha — APPROVED** [review]

**Comment by verbiricha** [comment]
Thanks!

**Pull request merged**
