### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by verbiricha**

### CODE REVIEW

**Review by v0l — APPROVED** [review]

**Comment by v0l** [comment]
DMS styles are affected: 
image

**Comment by verbiricha** [comment]
@v0l fixed in [bbbc334](https://github.com/v0l/snort/pull/55/commits/bbbc334b8501f31b55a065884f5173fae6245ccc)

**Review by v0l — COMMENTED** [review]
Can we replace `.note` styles in DM's so its the same?  Maybe create generic `.text` styles for the `Text` element

**Comment by verbiricha** [comment]
good point, addressed in https://github.com/v0l/snort/pull/55/commits/6aeaa6541d7bed155bf17000f585834c14b977ce

**Review by v0l — APPROVED** [review]
https://www.youtube.com/watch?v=gJPt38Bl_4I

**Pull request merged**
