### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by verbiricha**

### CODE REVIEW

**Comment by v0l** [comment]
Can you rebase this? there was some fixes on main

**Comment by verbiricha** [comment]
@v0l done!

**Review by v0l — APPROVED** [review]
Nice!

Can we make the buttons (QR/Settings) on the profile have a bit more padding, they are kinda small IMO

Also there is some issues with button overflowing the page: 
ui snort-social pages dev_(Samsung Galaxy S20 Ultra)

**Comment by v0l** [comment]
Also the footer tabs are hard to see i actually didnt notice them at all at first:
ui snort-social pages dev_p_npub1v0lxxxxutpvrelsksy8cdhgfux9l6a42hsj2qzquu2zk7vc9qnkszrqj49(Samsung Galaxy S20 Ultra)

**Comment by verbiricha** [comment]
Addressed your comments, lmk if you find anything else or dislike something.

**Comment by v0l** [comment]
> Addressed your comments, lmk if you find anything else or dislike something.

Looks good :shipit:

**Pull request merged**
