### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by verbiricha**
Not changed:
- Threads (designs wip, will tackle separately)
- Direct messages (no designs)
- Settings (no designs)

### CODE REVIEW

**Comment by v0l** [comment]
1. Login / Profile editor buttons still use old styles
2. Note creator clips under keyboard on android
3. Banner missing fade out

image
image
image

**Comment by v0l** [comment]
It seems like we're changing the design every few days lol, maybe we can do entire UI in one go so that it at least remains consistent for more than a few days, that said i do really like the new designs!

**Comment by verbiricha** [comment]
> It seems like we're changing the design every few days lol, maybe we can do entire UI in one go so that it at least remains consistent for more than a few days, that said i do really like the new designs!

😂 Yeah I'm going to do all in this PR, still work in progress

**Comment by verbiricha** [comment]
@v0l we still don't have designs for the screens i listed above, perhaps we should ship this and then improve those when we have the designs.

**Review by v0l — APPROVED** [review]

**Pull request merged**
