### PR TITLE
fix links in parentheses

### PR DESCRIPTION
**Pull request by SamSamskies**
resolves https://github.com/v0l/snort/issues/343

Screenshot 2023-02-21 at 6 59 42 PM

### CODE REVIEW

**Comment by SamSamskies** [comment]
Didn't dig into why, but for some reason this also fixed the rendering of the image.

**Comment by SamSamskies** [comment]
Wait, don't merge this. I think this broke some of the embedded players. Converting to draft.

**Comment by SamSamskies** [comment]
Actually embedded players are fine. I just had my settings set to not set not to display media from non-follows.

**Comment by SamSamskies** [comment]
This also fixes the bug where periods are being included at the end of a link https://fix-links-in-parentheses.snort-social.pages.dev/e/note1as9axphvvkhzagx62p5qgdh6jqq93d5f3pdueqpdwkf77y7ylqts8tuue2.

**Review by verbiricha — APPROVED** [review]

**Comment by v0l** [comment]
https://snort.social/e/note1qftjaj66tyu2ppsq62tscld96pll5agjczzjw4qy8l4enrjn968s4wjwgx

**Comment by SamSamskies** [comment]
doh i think it's time to add some unit tests. i'll make a quick fix and add unit tests later.

**Pull request merged**
